"""Tests for X2 — the audit-ready evidence-pack export."""

from __future__ import annotations

from pathlib import Path

from fastapi.testclient import TestClient

from app.connectors.config_store import ConnectorConfigStore
from app.main import create_app
from app.services.evidence_pack import build_evidence_pack, render_evidence_pack_html
from app.services.problems import ProblemStore
from app.services.seed import load_seed_problems
from app.services.telemetry import SQLiteTelemetryStore
from app.services.workflow import WorkflowStore


def _client(tmp_path: Path):
    telemetry = SQLiteTelemetryStore(tmp_path / "t.db")
    client = TestClient(
        create_app(
            problem_store=ProblemStore(load_seed_problems()),
            workflows=WorkflowStore(),
            connector_configs=ConnectorConfigStore(),
            telemetry=telemetry,
        )
    )
    return client, telemetry


class TestPackStructure:
    def test_pack_contains_all_sections(self) -> None:
        problem = load_seed_problems()[0]
        store = WorkflowStore()
        pack = build_evidence_pack(problem, store.state_for_problem(problem))

        assert pack["problem"]["problem_id"] == problem.problem_id
        assert len(pack["evidence"]) == len(problem.evidence)
        assert len(pack["actions"]) == len(problem.action_proposals)
        assert len(pack["governance_checks"]) == len(problem.governance_checks)
        assert pack["outcome"]["metric"] == problem.outcome_contract.primary_metric
        assert pack["approvals"] == [] and pack["executions"] == []

    def test_html_escapes_untrusted_feedback(self) -> None:
        problem = load_seed_problems()[0]
        hostile = problem.evidence[0].model_copy(
            update={"excerpt": '<script>alert("xss")</script>'}
        )
        problem = problem.model_copy(update={"evidence": [hostile, *problem.evidence[1:]]})
        store = WorkflowStore()

        html_doc = render_evidence_pack_html(
            build_evidence_pack(problem, store.state_for_problem(problem))
        )
        assert "<script>alert" not in html_doc
        assert "&lt;script&gt;" in html_doc

    def test_html_renders_key_fields(self) -> None:
        problem = load_seed_problems()[0]
        store = WorkflowStore()
        html_doc = render_evidence_pack_html(
            build_evidence_pack(problem, store.state_for_problem(problem))
        )
        assert problem.problem_id in html_doc
        assert problem.outcome_contract.primary_metric in html_doc
        assert "Governance" in html_doc and "Human approvals" in html_doc


class TestEvidencePackEndpoint:
    def test_html_export_includes_approval_and_execution_trail(self, tmp_path: Path) -> None:
        client, telemetry = _client(tmp_path)
        client.post(
            "/problems/PRB-108/approvals",
            json={"action_id": "ACT-501", "decision": "approved", "reviewer": "auditor"},
        )

        response = client.get("/problems/PRB-108/evidence-pack")
        assert response.status_code == 200
        assert response.headers["content-type"].startswith("text/html")
        body = response.text
        assert "Evidence Pack" in body
        assert "auditor" in body  # the approval trail is in the document
        assert "EXE-0001" in body  # so is the execution
        assert "Generated by CLARA" in body

        events = [e for e in telemetry.list_events() if e["event_type"] == "evidence_pack_exported"]
        assert len(events) == 1

    def test_json_format_returns_structured_pack(self, tmp_path: Path) -> None:
        client, _ = _client(tmp_path)
        response = client.get("/problems/PRB-108/evidence-pack?format=json")
        assert response.status_code == 200
        pack = response.json()
        assert pack["problem"]["problem_id"] == "PRB-108"
        assert "outcome" in pack and "governance_checks" in pack

    def test_unknown_problem_404s(self, tmp_path: Path) -> None:
        client, _ = _client(tmp_path)
        assert client.get("/problems/PRB-NOPE/evidence-pack").status_code == 404
