"use client";

import { useEffect, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import {
  authConfigured,
  confirmMfaEnrollment,
  cookieAuthEnabled,
  enrollMfa,
  listMfaFactors,
  removeMfaFactor,
  type MfaFactor,
} from "@/lib/auth-client";
import { apiBaseUrl, apiHeaders, getSystemConfig, getWorkspace, updateWorkspace } from "@/lib/client-api";
import type { SystemConfig, WorkspaceSettings } from "@/lib/types";
import { useI18n } from "@/lib/i18n";

const DEFAULTS: WorkspaceSettings = {
  name: "My Workspace",
  slug: "my-workspace",
  notification_email: "",
  measurement_window_days: 14,
  learning_half_life_days: 180,
  ai_disclosure_template:
    "Automatisch mit KI erstellt — von CLARA. / AI-generated by CLARA (EU AI Act Art. 50).",
  works_council_mode: false,
  ai_literacy_pack_delivered_at: null
};

type Status = { tone: "idle" | "busy" | "ok" | "error"; message: string };

export default function SettingsPage() {
  const { t } = useI18n();
  const [settings, setSettings] = useState<WorkspaceSettings>(DEFAULTS);
  const [config, setConfig] = useState<SystemConfig | null>(null);
  const [status, setStatus] = useState<Status>({ tone: "idle", message: "" });
  const [dirty, setDirty] = useState<Set<keyof WorkspaceSettings>>(new Set());

  const [workspaceLoaded, setWorkspaceLoaded] = useState(false);
  const [workspaceLoadFailed, setWorkspaceLoadFailed] = useState(false);
  const [aiUrl, setAiUrl] = useState("");
  const [aiModel, setAiModel] = useState("");
  const [aiEmbedModel, setAiEmbedModel] = useState("");
  const [aiKey, setAiKey] = useState("");
  const [aiBusy, setAiBusy] = useState(false);
  const [aiStatus, setAiStatus] = useState<{ tone: "ok" | "error"; text: string } | null>(null);

  async function saveAi() {
    setAiBusy(true);
    setAiStatus(null);
    try {
      const res = await fetch(`${apiBaseUrl()}/settings/ai`, {
        method: "PUT",
        credentials: "include", headers: apiHeaders(),
        body: JSON.stringify({ base_url: aiUrl, model: aiModel, embed_model: aiEmbedModel, api_key: aiKey }),
      });
      const data = await res.json().catch(() => null);
      if (!res.ok) throw new Error(data?.detail ?? `Save failed (${res.status})`);
      setAiKey("");
      setAiStatus(
        data?.warning
          ? { tone: "error", text: data.warning }
          : { tone: "ok", text: t.settings.aiSaved }
      );
      getSystemConfig().then(setConfig).catch(() => {});
    } catch (e) {
      setAiStatus({ tone: "error", text: e instanceof Error ? e.message : "Save failed" });
    } finally {
      setAiBusy(false);
    }
  }

  async function testAi() {
    setAiBusy(true);
    setAiStatus(null);
    try {
      const res = await fetch(`${apiBaseUrl()}/settings/ai/test`, { method: "POST", credentials: "include", headers: apiHeaders() });
      const data = await res.json().catch(() => null);
      if (data?.ok && data?.embed_ok === false)
        setAiStatus({ tone: "error", text: `${t.settings.aiTestEmbedFail} ${data.embed_error ?? data.embed_model}` });
      else if (data?.ok) setAiStatus({ tone: "ok", text: `${t.settings.aiTestOk} (${data.model})` });
      else setAiStatus({ tone: "error", text: `${t.settings.aiTestFail} ${data?.error ?? res.status}` });
    } catch (e) {
      setAiStatus({ tone: "error", text: e instanceof Error ? e.message : "Test failed" });
    } finally {
      setAiBusy(false);
    }
  }

  useEffect(() => {
    // If the load fails, saving would overwrite real workspace data with the
    // placeholder defaults; disable Save until a real read succeeds.
    getWorkspace()
      .then((data) => {
        setSettings(data);
        setWorkspaceLoaded(true);
        setWorkspaceLoadFailed(false);
      })
      .catch(() => setWorkspaceLoadFailed(true));
    getSystemConfig().then(setConfig).catch(() => {});
  }, []);

  function update<K extends keyof WorkspaceSettings>(key: K, value: WorkspaceSettings[K]) {
    setSettings((current) => ({ ...current, [key]: value }));
    setDirty((current) => new Set(current).add(key));
  }

  async function save() {
    setStatus({ tone: "busy", message: t.settings.saving });
    try {
      // Send only the fields edited in THIS tab: the API merges partial
      // payloads, so a stale tab cannot wipe flags or attestations written
      // elsewhere (e.g. the AI-literacy delivery attestation).
      const payload: Partial<WorkspaceSettings> = {};
      for (const key of dirty) {
        (payload as Record<string, unknown>)[key] = settings[key];
      }
      setSettings(await updateWorkspace(payload));
      setDirty(new Set());
      setStatus({ tone: "ok", message: t.settings.saved });
    } catch (error) {
      setStatus({ tone: "error", message: error instanceof Error ? error.message : t.settings.saveFailed });
    }
  }

  const busy = status.tone === "busy";

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold">{t.settings.title}</h1>
        <p className="text-sm text-muted-foreground mt-1">{t.settings.subtitle}</p>
        {workspaceLoadFailed ? (
          <p role="alert" className="mt-2 rounded-md border border-destructive/50 px-3 py-2 text-sm text-destructive">
            {t.common.error}
          </p>
        ) : null}
      </div>

      {status.message ? (
        <div
          className={`rounded-md border p-3 text-sm ${
            status.tone === "error"
              ? "border-destructive/40 bg-destructive/5 text-destructive"
              : status.tone === "ok"
                ? "border-emerald-500/40 bg-emerald-500/5 text-emerald-700 dark:text-emerald-400"
                : "border-border bg-muted text-muted-foreground"
          }`}
        >
          {status.message}
        </div>
      ) : null}

      <Card>
        <CardHeader>
          <CardTitle>{t.settings.workspace}</CardTitle>
          <CardDescription>{t.settings.workspaceSubtitle}</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div>
            <Label htmlFor="name">{t.settings.workspaceName}</Label>
            <Input
              id="name"
              className="mt-1"
              value={settings.name}
              onChange={(event) => update("name", event.target.value)}
            />
          </div>
          <div>
            <Label htmlFor="slug">{t.settings.slug}</Label>
            <Input
              id="slug"
              className="mt-1"
              value={settings.slug}
              onChange={(event) => update("slug", event.target.value)}
            />
          </div>
          <div>
            <Label htmlFor="email">{t.settings.notificationEmail}</Label>
            <Input
              id="email"
              type="email"
              className="mt-1"
              placeholder="alerts@company.com"
              value={settings.notification_email}
              onChange={(event) => update("notification_email", event.target.value)}
            />
          </div>
          <div>
            <Label htmlFor="disclosure">{t.settings.disclosureLabel}</Label>
            <Textarea
              id="disclosure"
              className="mt-1"
              value={settings.ai_disclosure_template}
              onChange={(event) => update("ai_disclosure_template", event.target.value)}
            />
            <p className="mt-1 text-xs text-muted-foreground">{t.settings.disclosureNote}</p>
          </div>
          <Button onClick={save} disabled={busy || workspaceLoadFailed || !workspaceLoaded}>
            {busy ? t.settings.saving : t.settings.saveChanges}
          </Button>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>{t.settings.measurement}</CardTitle>
          <CardDescription>{t.settings.measurementSubtitle}</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div>
            <Label htmlFor="window">{t.settings.windowDays}</Label>
            <Input
              id="window"
              type="number"
              className="mt-1"
              value={settings.measurement_window_days}
              onChange={(event) => {
                // Don't coerce an empty field to 0 (Number("") === 0); leave it unchanged.
                if (event.target.value !== "") update("measurement_window_days", Number(event.target.value));
              }}
            />
          </div>
          <div>
            <Label htmlFor="half-life">{t.settings.halfLifeDays}</Label>
            <Input
              id="half-life"
              type="number"
              className="mt-1"
              value={settings.learning_half_life_days}
              onChange={(event) => {
                if (event.target.value !== "") update("learning_half_life_days", Number(event.target.value));
              }}
            />
          </div>
          <Button onClick={save} disabled={busy || workspaceLoadFailed || !workspaceLoaded}>
            {busy ? t.settings.saving : t.settings.saveChanges}
          </Button>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>{t.settings.worksCouncil}</CardTitle>
          <CardDescription>{t.settings.worksCouncilSubtitle}</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <label className="flex items-start gap-2 text-sm">
            <input
              type="checkbox"
              className="mt-0.5"
              checked={settings.works_council_mode}
              onChange={(event) => update("works_council_mode", event.target.checked)}
            />
            <span>
              <span className="font-medium">{t.settings.worksCouncilLabel}</span>
              <span className="mt-1 block text-xs text-muted-foreground">{t.settings.worksCouncilNote}</span>
            </span>
          </label>
          <Button onClick={save} disabled={busy || workspaceLoadFailed || !workspaceLoaded}>
            {busy ? t.settings.saving : t.settings.saveChanges}
          </Button>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>{t.settings.aiConfig}</CardTitle>
          <CardDescription>{t.settings.aiConfigSubtitle}</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          {config ? (
            <div className="flex flex-wrap gap-4 text-sm">
              <span className="text-muted-foreground">
                {t.settings.authLabel}: <code className="rounded bg-muted px-2 py-0.5">{config.auth_enabled ? t.compliance.enabled : "disabled"}</code>
              </span>
              <span className="text-muted-foreground">
                Aktiv: <code className="rounded bg-muted px-2 py-0.5">{config.ai_model}</code> @ <code className="rounded bg-muted px-2 py-0.5">{config.ai_base_url}</code>
              </span>
            </div>
          ) : null}

          <div className="space-y-2">
            <Label htmlFor="ai-url">{t.settings.aiBaseUrl}</Label>
            <Input id="ai-url" value={aiUrl} onChange={(e) => setAiUrl(e.target.value)} placeholder="https://api.mistral.ai/v1 · http://localhost:11434/v1" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="ai-model">{t.settings.aiModel}</Label>
            <Input id="ai-model" value={aiModel} onChange={(e) => setAiModel(e.target.value)} placeholder="mistral-small-latest · qwen3:32b" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="ai-embed-model">{t.settings.aiEmbedModel}</Label>
            <Input id="ai-embed-model" value={aiEmbedModel} onChange={(e) => setAiEmbedModel(e.target.value)} placeholder="mistral-embed · nomic-embed-text" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="ai-key">{t.settings.aiApiKey}</Label>
            <Input id="ai-key" type="password" value={aiKey} onChange={(e) => setAiKey(e.target.value)} placeholder="sk-…" />
          </div>
          <p className="text-xs text-muted-foreground">
            {t.settings.aiPresets}{" "}
            <button type="button" className="underline underline-offset-2 hover:text-foreground" onClick={() => { setAiUrl("https://api.mistral.ai/v1"); setAiModel("mistral-small-latest"); setAiEmbedModel("mistral-embed"); }}>Mistral (EU)</button>
            {" · "}
            <button type="button" className="underline underline-offset-2 hover:text-foreground" onClick={() => { setAiUrl("http://localhost:11434/v1"); setAiModel("qwen3:32b"); setAiEmbedModel("nomic-embed-text"); }}>Ollama (local)</button>
            {" · "}
            <button type="button" className="underline underline-offset-2 hover:text-foreground" onClick={() => { setAiUrl("https://opencode.ai/zen/v1"); setAiModel("glm-5.2"); setAiEmbedModel("gemini-embedding-001"); }}>OpenCode Zen</button>
          </p>
          <div className="flex gap-2">
            <Button size="sm" onClick={saveAi} disabled={aiBusy}>
              {aiBusy ? t.settings.saving : t.settings.saveChanges}
            </Button>
            <Button size="sm" variant="outline" onClick={testAi} disabled={aiBusy}>
              {aiBusy ? t.settings.aiTesting : t.settings.aiTest}
            </Button>
          </div>
          {aiStatus ? (
            <p role="status" className={`text-sm ${aiStatus.tone === "ok" ? "text-emerald-600" : "text-destructive"}`}>
              {aiStatus.text}
            </p>
          ) : null}
          <p className="text-xs text-muted-foreground">{t.settings.aiConfigNote}</p>
        </CardContent>
      </Card>

      {cookieAuthEnabled && authConfigured ? <MfaCard /> : null}
    </div>
  );
}

function MfaCard() {
  const { t } = useI18n();
  const [factors, setFactors] = useState<MfaFactor[]>([]);
  const [enrollment, setEnrollment] = useState<{
    factorId: string;
    qrCode: string | null;
    secret: string | null;
  } | null>(null);
  const [code, setCode] = useState("");
  const [busy, setBusy] = useState(false);
  const [mfaStatus, setMfaStatus] = useState<{ tone: "ok" | "error"; text: string } | null>(null);

  async function refresh() {
    try {
      setFactors(await listMfaFactors());
    } catch {
      // Signed out or endpoint unavailable — card stays in its empty state.
    }
  }

  useEffect(() => {
    void refresh();
  }, []);

  async function beginEnrollment() {
    setBusy(true);
    setMfaStatus(null);
    try {
      setEnrollment(await enrollMfa());
      setCode("");
    } catch (error) {
      setMfaStatus({ tone: "error", text: error instanceof Error ? error.message : "Enrollment failed" });
    } finally {
      setBusy(false);
    }
  }

  async function confirmEnrollment() {
    if (!enrollment) return;
    setBusy(true);
    setMfaStatus(null);
    try {
      await confirmMfaEnrollment(enrollment.factorId, code.trim());
      setEnrollment(null);
      setCode("");
      setMfaStatus({ tone: "ok", text: t.settings.mfaEnabledNow });
      await refresh();
    } catch (error) {
      setMfaStatus({ tone: "error", text: error instanceof Error ? error.message : "Invalid code" });
    } finally {
      setBusy(false);
    }
  }

  async function remove(factorId: string) {
    if (!window.confirm(t.settings.mfaRemoveConfirm)) return;
    setBusy(true);
    try {
      await removeMfaFactor(factorId);
      await refresh();
      setMfaStatus(null);
    } catch (error) {
      setMfaStatus({ tone: "error", text: error instanceof Error ? error.message : "Could not remove" });
    } finally {
      setBusy(false);
    }
  }

  const verified = factors.filter((factor) => factor.status === "verified");

  return (
    <Card>
      <CardHeader>
        <CardTitle>{t.settings.mfaTitle}</CardTitle>
        <CardDescription>{t.settings.mfaSubtitle}</CardDescription>
      </CardHeader>
      <CardContent className="space-y-3">
        {verified.length > 0 ? (
          <div className="space-y-2">
            <p className="text-sm text-emerald-600">{t.settings.mfaEnabled}</p>
            {verified.map((factor) => (
              <div key={factor.id} className="flex items-center justify-between rounded-md border px-3 py-2 text-sm">
                <span>{factor.friendlyName || "TOTP"} · {factor.factorType}</span>
                <Button size="sm" variant="ghost" disabled={busy} onClick={() => remove(factor.id)}>
                  {t.settings.mfaRemove}
                </Button>
              </div>
            ))}
          </div>
        ) : enrollment ? (
          <div className="space-y-3">
            <p className="text-sm text-muted-foreground">{t.settings.mfaScan}</p>
            {enrollment.qrCode ? (
              // GoTrue returns the QR as an SVG string; render it as a data URL.
              // eslint-disable-next-line @next/next/no-img-element
              <img
                alt="TOTP QR code"
                width={176}
                height={176}
                src={`data:image/svg+xml;utf8,${encodeURIComponent(enrollment.qrCode)}`}
              />
            ) : null}
            {enrollment.secret ? (
              <p className="text-xs text-muted-foreground">
                {t.settings.mfaSecret}: <code className="bg-muted px-1.5 py-0.5 rounded select-all">{enrollment.secret}</code>
              </p>
            ) : null}
            <div className="flex items-end gap-2">
              <div>
                <Label htmlFor="mfa-enroll-code">{t.settings.mfaCodeLabel}</Label>
                <Input
                  id="mfa-enroll-code"
                  className="mt-1 w-32"
                  inputMode="numeric"
                  maxLength={6}
                  value={code}
                  onChange={(event) => setCode(event.target.value)}
                />
              </div>
              <Button size="sm" disabled={busy || code.trim().length < 6} onClick={confirmEnrollment}>
                {t.settings.mfaConfirm}
              </Button>
              <Button size="sm" variant="ghost" disabled={busy} onClick={() => setEnrollment(null)}>
                Cancel
              </Button>
            </div>
          </div>
        ) : (
          <div className="flex items-center justify-between gap-3">
            <p className="text-sm text-muted-foreground">{t.settings.mfaDisabledNote}</p>
            <Button size="sm" disabled={busy} onClick={beginEnrollment}>
              {t.settings.mfaEnable}
            </Button>
          </div>
        )}
        {mfaStatus ? (
          <p role="status" className={`text-sm ${mfaStatus.tone === "ok" ? "text-emerald-600" : "text-destructive"}`}>
            {mfaStatus.text}
          </p>
        ) : null}
      </CardContent>
    </Card>
  );
}
