from __future__ import annotations

import re
from datetime import UTC, datetime, timedelta
from enum import Enum
from typing import Any, Literal

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    computed_field,
    field_validator,
    model_validator,
)


class ProblemStatus(str, Enum):
    approval_needed = "approval_needed"
    blocked_by_policy = "blocked_by_policy"
    validation_required = "validation_required"
    in_progress = "in_progress"
    resolved = "resolved"


class TaxonomyType(str, Enum):
    product = "product"
    journey = "journey"
    contact_reason = "contact_reason"
    marketing = "marketing"
    compliance = "compliance"


class TaxonomyOperation(str, Enum):
    merge = "merge"
    split = "split"
    rename = "rename"
    lock = "lock"
    propose = "propose"
    review = "review"


class TaxonomyChange(BaseModel):
    change_id: str
    operation: TaxonomyOperation
    description: str
    actor: str
    changed_at: str


class TaxonomyCategory(BaseModel):
    category_id: str
    label: str
    description: str
    terms: list[str] = Field(default_factory=list)
    parent_id: str | None = None
    locked: bool = False
    status: str = "active"
    change_history: list[TaxonomyChange] = Field(default_factory=list)
    # Set on bootstrap-proposed categories: cluster cohesion (0..1) and how many
    # signals back the proposal. None for seed/manual categories.
    confidence: float | None = None
    evidence_count: int | None = None


class TaxonomyCatalog(BaseModel):
    taxonomy_type: TaxonomyType
    version: str
    locale_support: list[str]
    categories: list[TaxonomyCategory]
    known_limitations: list[str] = Field(default_factory=list)


class TaxonomyClassification(BaseModel):
    taxonomy_type: TaxonomyType
    category_id: str
    label: str
    confidence: float = Field(ge=0.0, le=1.0)
    evidence_signal_ids: list[str] = Field(default_factory=list)
    matched_terms: list[str] = Field(default_factory=list)
    language_notes: list[str] = Field(default_factory=list)
    limitations: list[str] = Field(default_factory=list)
    contradictory_evidence: list[str] = Field(default_factory=list)


class TerminologyDictionaryEntry(BaseModel):
    term_id: str
    canonical_term: str
    aliases: list[str] = Field(default_factory=list)
    languages: list[str] = Field(default_factory=list)
    taxonomy_type: TaxonomyType
    category_ids: list[str] = Field(default_factory=list)
    definition: str
    usage_notes: list[str] = Field(default_factory=list)


class RootCauseEvidenceFactor(BaseModel):
    factor_type: str
    label: str
    confidence: float = Field(ge=0.0, le=1.0)
    signal_ids: list[str] = Field(default_factory=list)
    explanation: str


class RootCauseAnalysis(BaseModel):
    hypothesis: str
    confidence: float = Field(ge=0.0, le=1.0)
    factors: list[RootCauseEvidenceFactor] = Field(default_factory=list)
    alternative_hypotheses: list[str] = Field(default_factory=list)
    validation_questions: list[str] = Field(default_factory=list)


class TaxonomyRenameRequest(BaseModel):
    category_id: str
    label: str = Field(min_length=1)
    description: str | None = None
    actor: str = "taxonomy_owner"


class TaxonomyReviewRequest(BaseModel):
    category_id: str
    decision: str  # "accept" | "reject" (validated in the store)
    actor: str = "taxonomy_owner"


class TaxonomyLockRequest(BaseModel):
    category_id: str
    actor: str = "taxonomy_owner"


class TaxonomyMergeRequest(BaseModel):
    source_category_ids: list[str] = Field(min_length=2)
    target_category_id: str
    target_label: str | None = None
    target_description: str | None = None
    actor: str = "taxonomy_owner"


class TaxonomySplitCategoryRequest(BaseModel):
    category_id: str
    label: str = Field(min_length=1)
    description: str = Field(min_length=1)
    terms: list[str] = Field(default_factory=list)


class TaxonomySplitRequest(BaseModel):
    source_category_id: str
    categories: list[TaxonomySplitCategoryRequest] = Field(min_length=2)
    actor: str = "taxonomy_owner"


class WorkspaceSettings(BaseModel):
    name: str = "My Workspace"
    slug: str = "my-workspace"
    notification_email: str = ""
    measurement_window_days: int = 14
    learning_half_life_days: int = 180
    # Industry profile retunes impact prioritisation (see industry_profiles.py).
    # Persisted per workspace; the active global scorer reads env INDUSTRY_PROFILE.
    industry_profile: str = "default"
    # EU AI Act Art. 50: appended to any outbound text that was NOT human-reviewed
    # (Art. 50(4) exempts reviewed content, so approved pushes carry no line).
    ai_disclosure_template: str = (
        "Automatisch mit KI erstellt — von CLARA. / "
        "AI-generated by CLARA (EU AI Act Art. 50)."
    )
    # Four-eyes approvals (opt-in): an action needs TWO distinct approvers
    # before execution — the first approval holds, the second (different
    # reviewer) releases. Enforcement lives in workflow.resolve_approval_state.
    four_eyes_approval: bool = False
    # Betriebsrat-Modus (§87(1) Nr. 6 BetrVG): below-admin read responses replace
    # person-capable fields (reviewer/actor/owner/assignee) with fixed role
    # labels. The entire policy lives in services/works_council.py.
    works_council_mode: bool = False
    # EU AI Act Art. 4: ISO date the AI-Literacy Pack was attested as delivered
    # to staff. Deliberately workspace-level only — per-user completion tracking
    # would be an employee-monitoring feature (works-council trap, conflicts
    # with the Betriebsrat-Modus guarantee above), so it does not exist here.
    ai_literacy_pack_delivered_at: str | None = None


class SystemConfig(BaseModel):
    ai_base_url: str
    ai_model: str
    ai_embed_model: str = ""
    # Equal to ai_base_url unless AI_EMBED_BASE_URL splits embeddings onto their
    # own provider. Exposed because a mismatch here is invisible otherwise.
    ai_embed_base_url: str = ""
    auth_enabled: bool


class ActionClass(str, Enum):
    structural = "structural"
    customer_recovery = "customer_recovery"
    journey_intervention = "journey_intervention"
    research = "research"
    governance = "governance"


class RiskLevel(str, Enum):
    low = "low"
    medium = "medium"
    high = "high"
    critical = "critical"


class GovernanceStatus(str, Enum):
    pass_ = "pass"
    fail = "fail"
    review_required = "review_required"


class ApprovalDecisionStatus(str, Enum):
    approved = "approved"
    rejected = "rejected"
    needs_more_evidence = "needs_more_evidence"


class ExecutionStatus(str, Enum):
    draft_created = "draft_created"
    blocked = "blocked"
    not_started = "not_started"
    completed = "completed"
    pushed = "pushed"
    push_failed = "push_failed"


class LearningStatus(str, Enum):
    worked = "worked"
    partially_worked = "partially_worked"
    did_not_work = "did_not_work"
    inconclusive = "inconclusive"
    measurement_invalid = "measurement_invalid"


class ImpactFactors(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    customer_reach: float = Field(ge=0.0, le=1.0)
    severity: float = Field(ge=0.0, le=1.0)
    recurrence: float = Field(ge=0.0, le=1.0)
    journey_criticality: float = Field(ge=0.0, le=1.0)
    account_exposure: float = Field(ge=0.0, le=1.0)
    financial_exposure: float = Field(ge=0.0, le=1.0)
    regulatory_risk: float = Field(ge=0.0, le=1.0)
    evidence_confidence: float = Field(ge=0.0, le=1.0)


class ImpactDriver(BaseModel):
    """One factor's share of the impact score, for display beside it.

    ``share`` is the factor's weighted term over the total weighted score, so
    the full set sums to 1.0. Presented to the approver so the priority can be
    questioned rather than merely read (Art 14 oversight, §4.4).
    """

    factor: str
    share: float = Field(ge=0.0, le=1.0)


class Evidence(BaseModel):
    signal_id: str
    source: str
    language: str
    excerpt: str
    customer_id: str
    account_id: str
    timestamp: str


class AffectedCohort(BaseModel):
    customers: int = Field(ge=0)
    accounts: int = Field(ge=0)
    high_value_accounts: int = Field(ge=0)
    date_range: str


class JourneyEventRecord(BaseModel):
    event_id: str = Field(min_length=1)
    customer_id: str = Field(min_length=1)
    account_id: str = Field(min_length=1)
    journey: str = Field(min_length=1)
    journey_stage: str = Field(min_length=1)
    event_name: str = Field(min_length=1)
    event_type: str = "behavior"
    timestamp: str
    success: bool | None = None
    duration_seconds: float | None = Field(default=None, ge=0.0)
    metadata: dict[str, str] = Field(default_factory=dict)


class JourneyEventImportRequest(BaseModel):
    events: list[JourneyEventRecord]


class JourneyEventCsvImportRequest(BaseModel):
    csv_text: str = Field(min_length=1)


class JourneyEventImportResult(BaseModel):
    imported: int
    skipped_duplicates: int
    total_events: int


class JourneyImpactSummary(BaseModel):
    matched_events: int = Field(ge=0)
    matched_customers: int = Field(ge=0)
    matched_accounts: int = Field(ge=0)
    friction_events: int = Field(ge=0)
    deviation_score: float = Field(ge=0.0, le=1.0)
    top_event_names: list[str] = Field(default_factory=list)
    drivers: list[str] = Field(default_factory=list)


class ContextImpactSummary(BaseModel):
    matched_customers: int = Field(ge=0)
    matched_accounts: int = Field(ge=0)
    high_value_accounts: int = Field(ge=0)
    total_account_value: float = Field(ge=0.0)
    average_health_score: float | None = Field(default=None, ge=0.0, le=1.0)
    consent_risk_customers: int = Field(ge=0)
    renewal_risk_accounts: int = Field(default=0, ge=0)
    priority_lifecycle_accounts: int = Field(default=0, ge=0)
    at_risk_lifecycle_accounts: int = Field(default=0, ge=0)
    owners: list[str] = Field(default_factory=list)
    product_owners: list[str] = Field(default_factory=list)
    regions: list[str] = Field(default_factory=list)
    score_delta: float = Field(default=0.0, ge=0.0, le=1.0)
    drivers: list[str] = Field(default_factory=list)


class AudienceReadiness(BaseModel):
    estimated_audience_size: int = Field(ge=0)
    eligible_customers: int = Field(ge=0)
    excluded_customers: int = Field(ge=0)
    consent_ready_customers: int = Field(ge=0)
    suppression_excluded_customers: int = Field(ge=0)
    over_contact_risk: Literal["low", "medium", "high"]
    readiness_status: Literal["ready_for_review", "needs_consent_review", "blocked_by_policy"]
    readiness_reasons: list[str] = Field(default_factory=list)
    export_destination: str = Field(min_length=1)
    export_format: str = Field(min_length=1)
    export_fields: list[str] = Field(default_factory=list)
    activation_constraints: list[str] = Field(default_factory=list)

    @model_validator(mode="after")
    def counts_must_be_consistent(self) -> "AudienceReadiness":
        if self.eligible_customers + self.excluded_customers != self.estimated_audience_size:
            raise ValueError("eligible and excluded customers must equal estimated audience size")
        if self.consent_ready_customers > self.estimated_audience_size:
            raise ValueError("consent-ready customers cannot exceed estimated audience size")
        if self.suppression_excluded_customers > self.excluded_customers:
            raise ValueError("suppression exclusions cannot exceed excluded customers")
        if self.readiness_status == "ready_for_review" and self.eligible_customers == 0:
            raise ValueError("ready audiences must include at least one eligible customer")
        if self.readiness_status == "ready_for_review" and self.eligible_customers > self.consent_ready_customers:
            raise ValueError("ready audiences require consent coverage for every eligible customer")
        return self


class InterventionBrief(BaseModel):
    audience_summary: str = Field(min_length=1)
    inclusion_criteria: list[str] = Field(default_factory=list)
    exclusion_criteria: list[str] = Field(default_factory=list)
    trigger: str = Field(min_length=1)
    recommended_channel: str = Field(min_length=1)
    content_brief: str = Field(min_length=1)
    personalization_variables: list[str] = Field(default_factory=list)
    control_group: str = Field(min_length=1)
    primary_success_metric: str = Field(min_length=1)
    guardrail_metrics: list[str] = Field(default_factory=list)
    consent_notes: list[str] = Field(default_factory=list)
    governance_notes: list[str] = Field(default_factory=list)
    audience_readiness: AudienceReadiness | None = None


class ActionProposalSnapshot(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    action_id: str
    class_: ActionClass = Field(alias="class")
    owner: str
    destination: str
    proposal: str
    risk_level: RiskLevel
    approval_state: str
    depends_on: list[str] = Field(default_factory=list)
    intervention_brief: InterventionBrief | None = None


class ActionProposalChange(BaseModel):
    field: str
    before: str
    after: str


class ActionProposal(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    action_id: str
    class_: ActionClass = Field(alias="class")
    owner: str
    destination: str
    proposal: str
    risk_level: RiskLevel
    approval_state: str
    depends_on: list[str] = Field(default_factory=list)
    intervention_brief: InterventionBrief | None = None
    original_snapshot: ActionProposalSnapshot | None = None


class GovernanceCheck(BaseModel):
    check_id: str
    rule: str
    policy_rule_id: str | None = None
    status: GovernanceStatus
    reason: str
    blocking: bool


class PolicyRule(BaseModel):
    rule_id: str = Field(min_length=1)
    title: str = Field(min_length=1)
    description: str = Field(min_length=1)
    category: str = Field(min_length=1)
    severity: RiskLevel
    applies_to_action_classes: list[ActionClass] = Field(default_factory=list)
    applies_to_destinations: list[str] = Field(default_factory=list)
    required_evidence: list[str] = Field(default_factory=list)
    default_blocking: bool
    owner: str = Field(min_length=1)
    version: str = Field(min_length=1)
    status: str = "active"


class OutcomeContract(BaseModel):
    primary_metric: str
    baseline: float
    success_threshold: float
    measurement_window_days: int = Field(gt=0)
    comparison_method: str
    guardrail_metrics: list[str]
    responsible_owner: str


class ProblemRecord(BaseModel):
    problem_id: str
    title: str
    statement: str
    journey: str
    journey_stage: str
    owner: str
    status: ProblemStatus
    impact_factors: ImpactFactors
    evidence_confidence: float = Field(ge=0.0, le=1.0)
    affected_cohort: AffectedCohort
    root_cause_hypothesis: str
    known_limitations: list[str]
    evidence: list[Evidence]
    action_proposals: list[ActionProposal]
    governance_checks: list[GovernanceCheck]
    outcome_contract: OutcomeContract
    impact_score: float | None = Field(default=None, ge=0.0, le=1.0)
    impact_band: str | None = None
    approval_pressure: str | None = None
    context_impact: ContextImpactSummary | None = None
    journey_impact: JourneyImpactSummary | None = None

    @computed_field  # type: ignore[prop-decorator]
    @property
    def impact_drivers(self) -> list[ImpactDriver]:
        """Which factors produced ``impact_score`` — derived, never stored.

        Deliberately computed rather than persisted: industry profiles re-weight
        the factors, so a stored ranking would silently go stale the moment a
        workspace switched profile, and would then explain the score with the
        wrong reasons. Deriving it keeps one source of truth (``impact_factors``).
        """
        from app.domain.scoring import impact_drivers as _drivers

        return [
            ImpactDriver(factor=factor, share=share)
            for factor, share in _drivers(self.impact_factors.model_dump())
        ]


class ProblemSummary(BaseModel):
    problem_id: str
    title: str
    journey: str
    journey_stage: str
    owner: str
    status: ProblemStatus
    impact_score: float
    impact_band: str
    impact_drivers: list[ImpactDriver] = Field(default_factory=list)
    evidence_confidence: float
    affected_customers: int
    affected_accounts: int
    approval_pressure: str
    top_action_classes: list[ActionClass]
    context_impact: ContextImpactSummary | None = None
    journey_impact: JourneyImpactSummary | None = None


class ProblemUpdateRequest(BaseModel):
    title: str | None = Field(default=None, min_length=1)
    statement: str | None = Field(default=None, min_length=1)
    owner: str | None = Field(default=None, min_length=1)
    root_cause_hypothesis: str | None = Field(default=None, min_length=1)


class ActionProposalUpdateRequest(BaseModel):
    owner: str | None = Field(default=None, min_length=1)
    destination: str | None = Field(default=None, min_length=1)
    proposal: str | None = Field(default=None, min_length=1)
    risk_level: RiskLevel | None = None
    approval_state: str | None = Field(default=None, min_length=1)
    intervention_brief: InterventionBrief | None = None


class OutcomeContractUpdateRequest(BaseModel):
    primary_metric: str | None = Field(default=None, min_length=1)
    baseline: float | None = None
    success_threshold: float | None = None
    measurement_window_days: int | None = Field(default=None, gt=0)
    comparison_method: str | None = Field(default=None, min_length=1)
    guardrail_metrics: list[str] | None = None
    responsible_owner: str | None = Field(default=None, min_length=1)


class OutcomeContractProposalPreview(BaseModel):
    """What approving with accept_proposed_contract=True would apply."""

    problem_id: str
    current: OutcomeContract
    proposed: OutcomeContract | None = None
    is_promotion_default: bool
    # Honest MDE heuristic for the proposed window (outcome_engine.detectability_note);
    # None when the baseline rate makes the estimate meaningless.
    detectability_note: str | None = None


class ProblemTransitionRequest(BaseModel):
    target_status: ProblemStatus
    actor: str = Field(min_length=1)
    note: str | None = Field(default=None, min_length=1)


class ProblemTransitionRecord(BaseModel):
    transition_id: str
    problem_id: str
    from_status: ProblemStatus
    to_status: ProblemStatus
    actor: str
    note: str | None = None
    created_at: str


class TimelineEvent(BaseModel):
    event_id: str
    problem_id: str
    event_type: str
    label: str
    detail: str
    actor: str | None = None
    created_at: str


class ApprovalDecision(BaseModel):
    action_id: str
    decision: ApprovalDecisionStatus
    reviewer: str
    note: str | None = None
    # W4 zero-input closure: approving applies the auto-proposed outcome
    # contract (trailing-28d baseline, 30d window, ITS scoring) unless the
    # reviewer opts out.
    accept_proposed_contract: bool = True


class ApprovalRecord(ApprovalDecision):
    decision_id: str
    problem_id: str
    created_at: str
    action_snapshot: ActionProposalSnapshot | None = None
    action_diff: list[ActionProposalChange] = Field(default_factory=list)
    # Content hash of the evidence pack as it stood when this decision was made
    # (set server-side, never from the request body). Re-exporting and comparing
    # hashes proves whether the pack the approver saw has since changed.
    # ponytail: hash-only tamper evidence; full frozen pack copies if audits demand.
    evidence_pack_hash: str | None = None


class ExecutionRecord(BaseModel):
    execution_id: str
    problem_id: str
    action_id: str
    destination: str
    status: ExecutionStatus
    owner: str
    summary: str
    created_at: str
    # Real-push audit trail: the external system's id (e.g. Jira issue key) and a
    # human-readable outcome/error note. None while the execution is a local draft.
    external_ref: str | None = None
    detail: str | None = None
    # EU AI Act Art. 50(4) editorial-review stamp: executions born from a human
    # approval carry the reviewer + approval timestamp; anything else is
    # auto-published and gets the AI-disclosure line on push (disclosure_applied).
    human_reviewed: bool = False
    reviewed_by: str | None = None
    reviewed_at: str | None = None
    disclosure_applied: bool = False


class JiraIssueDraft(BaseModel):
    draft_id: str
    problem_id: str
    action_id: str
    execution_id: str
    project_key: str
    issue_type: str
    summary: str
    description: str
    labels: list[str]
    assignee: str
    status: str
    created_at: str


class GuardrailMeasurement(BaseModel):
    """A non-inferiority readout for one declared guardrail metric.

    status: "ok" (not worse than baseline within tolerance), "breach"
    (worsened beyond the threshold — informative, never blocking), or
    "no_data_source" (declared but unmeasurable — surfaced explicitly so
    guardrails can never silently stay decorative)."""

    guardrail_id: str
    problem_id: str
    metric: str
    status: str
    observed_value: float | None = None
    baseline: float | None = None
    measured_at: str
    note: str | None = None


class OutcomeMeasurement(BaseModel):
    problem_id: str
    metric: str
    observed_value: float
    measured_at: str
    notes: str | None = None
    # Provenance: "instrumented" only when the measurement scheduler computed the
    # value from raw signals; anything hand-entered stays "manual" so the UI can
    # label it an unverified manual observation (never visually conflated).
    measurement_source: str = "manual"


LEARNING_RETENTION_DAYS = 730


def retention_expires_at(created_at: str, days: int = LEARNING_RETENTION_DAYS) -> str:
    created = datetime.fromisoformat(created_at.replace("Z", "+00:00"))
    expires_at = (created + timedelta(days=days)).astimezone(UTC)
    return expires_at.isoformat().replace("+00:00", "Z")


def redact_common_pii(value: str | None) -> str | None:
    if value is None:
        return None

    redacted = value
    patterns = [
        (r"\b\S+@\S+\b", "[EMAIL REDACTED]"),
        (r"\b(?:\d{1,3}\.){3}\d{1,3}\b", "[IP REDACTED]"),
        (r"(?<!\w)(?:\+?\d[\d .()/-]{7,}\d)(?!\w)", "[PHONE REDACTED]"),
        (r"\b(?:CUST|CUSTOMER|ACC|ACCOUNT)-[A-Za-z0-9_-]+\b", "[ID REDACTED]"),
        (
            r"\b\d{1,6}\s+[A-Za-z0-9 .'-]+\s+"
            r"(?:Street|St|Avenue|Ave|Road|Rd|Boulevard|Blvd|Lane|Ln|Drive|Dr)\b",
            "[ADDRESS REDACTED]",
        ),
    ]
    for pattern, replacement in patterns:
        redacted = re.sub(pattern, replacement, redacted, flags=re.IGNORECASE)
    return redacted.strip()


def pseudonymized_identifier(value: str, field_name: str) -> str:
    redacted = redact_common_pii(value)
    if not redacted:
        raise ValueError(f"{field_name} is required.")
    if redacted != value.strip():
        raise ValueError(f"{field_name} must be a pseudonymized identifier.")
    return redacted


class ClosureRecordRequest(BaseModel):
    operational_status: Literal["not_started", "draft_created", "in_progress", "released", "verified"]
    customer_status: Literal["not_started", "not_eligible", "draft_ready", "contacted", "unresolved"]
    owner: str = Field(min_length=1)
    verified_resolution_facts: list[str] = Field(min_length=1)
    unresolved_customers: int = Field(ge=0)
    follow_up_channel: str = Field(min_length=1)
    response_draft: str | None = Field(default=None, max_length=2000)
    limitations: list[str] = Field(default_factory=list)

    @field_validator("owner", "follow_up_channel", "response_draft")
    @classmethod
    def redact_text_fields(cls, value: str | None) -> str | None:
        redacted = redact_common_pii(value)
        if value is not None and not redacted:
            raise ValueError("Text fields cannot be blank.")
        return redacted

    @field_validator("verified_resolution_facts", "limitations")
    @classmethod
    def redact_list_text(cls, values: list[str]) -> list[str]:
        cleaned: list[str] = []
        for value in values:
            redacted = redact_common_pii(value)
            if not redacted:
                raise ValueError("Text fields cannot be blank.")
            cleaned.append(redacted)
        return cleaned

    @model_validator(mode="after")
    def customer_closure_needs_verified_facts(self) -> "ClosureRecordRequest":
        if self.customer_status in {"draft_ready", "contacted"} and self.operational_status not in {"released", "verified"}:
            raise ValueError("customer closure requires released or verified operational status")
        if self.customer_status == "contacted" and self.response_draft is None:
            raise ValueError("contacted closure records require the reviewed response text")
        return self


class ClosureRecord(ClosureRecordRequest):
    closure_id: str
    problem_id: str
    tenant_id: str
    actor: str
    customer_closure_eligible: bool
    created_at: str

    @field_validator("tenant_id", "actor")
    @classmethod
    def identifiers_must_be_pseudonymized(cls, value: str) -> str:
        return pseudonymized_identifier(value, "Identifier")


class LearningConclusionRequest(BaseModel):
    learning_status: LearningStatus
    summary: str = Field(min_length=1, max_length=2000)
    limitations: str = Field(min_length=1, max_length=2000)
    next_step: str | None = Field(default=None, max_length=1000)

    @field_validator("summary", "limitations", "next_step")
    @classmethod
    def redact_free_text(cls, value: str | None) -> str | None:
        # ponytail: stdlib heuristics only; dedicated DSR tooling if free text expands.
        redacted = redact_common_pii(value)
        if value is not None and not redacted:
            raise ValueError("Text fields cannot be blank.")
        return redacted


class LearningConclusionRecord(LearningConclusionRequest):
    conclusion_id: str
    problem_id: str
    tenant_id: str
    reviewer: str
    reviewed_at: str
    retention_expires_at: str

    @field_validator("tenant_id", "reviewer")
    @classmethod
    def identifiers_must_be_pseudonymized(cls, value: str) -> str:
        return pseudonymized_identifier(value, "Identifier")


class OutcomeSnapshot(BaseModel):
    problem_id: str
    metric: str
    baseline: float
    success_threshold: float
    latest_value: float | None = None
    status: str
    improvement_direction: Literal["increase", "decrease"]
    measurement_window_days: int
    comparison_method: str
    # Provenance of latest_value ("instrumented" | "manual"), None when unmeasured.
    measurement_source: str | None = None
    # A–E design grade (outcome_engine.evidence_grade): A holdout, C ITS,
    # D before/after, E manual/unmeasured.
    evidence_grade: str | None = None
    # Latest readout per declared guardrail metric (non-inferiority checks).
    guardrails: list[GuardrailMeasurement] = Field(default_factory=list)
    # W4 read-time ITS scoring (outcome_engine.its_outcome_for_problem):
    # either {method: "its", effect, ci_low, ci_high, ...} or the honest
    # sparse fallback {method: "delta_insufficient_data", label, delta, ...}.
    its: dict[str, Any] | None = None


class OutcomeBoardItem(BaseModel):
    problem_id: str
    title: str
    owner: str
    problem_status: ProblemStatus
    impact_score: float
    impact_band: str
    metric: str
    baseline: float
    success_threshold: float
    latest_value: float | None = None
    outcome_status: str
    improvement_direction: Literal["increase", "decrease"]
    latest_learning_status: LearningStatus | None = None
    latest_learning_reviewed_at: str | None = None
    measurement_window_days: int
    comparison_method: str
    responsible_owner: str
    measurement_source: str | None = None
    evidence_grade: str | None = None
    guardrails: list[GuardrailMeasurement] = Field(default_factory=list)


class OutcomeBoard(BaseModel):
    total: int
    not_measured: int
    not_improved: int
    improving: int
    target_met: int
    learning_worked: int = 0
    learning_partially_worked: int = 0
    learning_did_not_work: int = 0
    learning_inconclusive: int = 0
    learning_measurement_invalid: int = 0
    items: list[OutcomeBoardItem]


class WorkflowState(BaseModel):
    problem_id: str
    approvals: list[ApprovalRecord]
    executions: list[ExecutionRecord]
    jira_issue_drafts: list[JiraIssueDraft]
    outcome: OutcomeSnapshot
    learning_conclusions: list[LearningConclusionRecord]
    closure_records: list[ClosureRecord] = Field(default_factory=list)
    timeline: list[TimelineEvent]


class SignalRecord(BaseModel):
    # Only signal_id (primary key) and feedback_text are required; every other field has a
    # sensible default so arbitrary CSVs import. Unmapped columns are kept in `metadata`.
    signal_id: str
    feedback_text: str
    customer_id: str = "unknown_customer"
    account_id: str = "unknown_account"
    source: str = "csv_upload"
    journey: str = "unknown_journey"
    journey_stage: str = "unknown_stage"
    campaign_exposure: list[str] = Field(default_factory=list)
    product_events: list[str] = Field(default_factory=list)
    language: str = "unknown"
    timestamp: str = "1970-01-01T00:00:00Z"
    metadata: dict[str, str] = Field(default_factory=dict)
    # Enrichment written back by the triage pipeline. Without persistence the
    # feed's "Enriched" tile was permanently 0 and sentiment/urgency badges
    # never rendered (enrichment lived only inside the triage graph state).
    sentiment: str | None = None
    urgency: str | None = None
    tags: list[str] = Field(default_factory=list)
    enriched: bool = False


class SignalImportRequest(BaseModel):
    signals: list[SignalRecord]


class SignalCsvImportRequest(BaseModel):
    csv_text: str = Field(min_length=1)


class SignalValidationIssue(BaseModel):
    severity: str
    row_number: int | None = None
    field: str | None = None
    message: str


class SignalValidationReport(BaseModel):
    valid: bool
    total_rows: int
    importable_rows: int
    errors: list[SignalValidationIssue]
    warnings: list[SignalValidationIssue]


class SignalImportResult(BaseModel):
    imported: int
    skipped_duplicates: int
    total_signals: int


class CandidateReviewStatus(str, Enum):
    pending = "pending"
    duplicate = "duplicate"
    accepted = "accepted"
    rejected = "rejected"


class CandidateDecisionStatus(str, Enum):
    accepted = "accepted"
    rejected = "rejected"


class CandidateReviewRequest(BaseModel):
    reviewer: str = Field(min_length=1)
    note: str | None = Field(default=None, min_length=1)


class CandidateDecisionRecord(BaseModel):
    candidate_id: str
    decision: CandidateDecisionStatus
    reviewer: str
    note: str | None = None
    created_at: str


class CustomerContextRecord(BaseModel):
    customer_id: str = Field(min_length=1)
    account_id: str = Field(min_length=1)
    account_name: str | None = None
    parent_account_id: str | None = None
    parent_account_name: str | None = None
    segment: str | None = None
    lifecycle_stage: str | None = None
    plan_tier: str | None = None
    contact_role: str | None = None
    account_value: float = Field(default=0.0, ge=0.0)
    renewal_date: str | None = None
    consent_status: str = "unknown"
    health_score: float | None = Field(default=None, ge=0.0, le=1.0)
    owner: str | None = None
    product_owner: str | None = None
    region: str | None = None


class ContextDataQualityWarning(BaseModel):
    warning_id: str
    severity: str
    field: str
    message: str
    customer_ids: list[str] = Field(default_factory=list)
    account_ids: list[str] = Field(default_factory=list)


class ContextRoutingRecommendation(BaseModel):
    owner: str
    priority: str
    reason: str
    customer_ids: list[str] = Field(default_factory=list)
    account_ids: list[str] = Field(default_factory=list)
    contact_roles: list[str] = Field(default_factory=list)


class AffectedAccountSummary(BaseModel):
    account_id: str
    account_name: str | None = None
    parent_account_id: str | None = None
    parent_account_name: str | None = None
    customer_count: int = Field(ge=0)
    account_value: float = Field(ge=0.0)
    high_value: bool
    consent_risk_customers: int = Field(ge=0)
    average_health_score: float | None = Field(default=None, ge=0.0, le=1.0)
    contact_roles: list[str] = Field(default_factory=list)
    lifecycle_stages: list[str] = Field(default_factory=list)
    plan_tiers: list[str] = Field(default_factory=list)
    renewal_dates: list[str] = Field(default_factory=list)
    owners: list[str] = Field(default_factory=list)
    product_owners: list[str] = Field(default_factory=list)
    regions: list[str] = Field(default_factory=list)


class AffectedContextExplorer(BaseModel):
    problem_id: str
    context_impact: ContextImpactSummary | None = None
    accounts: list[AffectedAccountSummary]
    customers: list[CustomerContextRecord]
    missing_customer_ids: list[str]
    missing_account_ids: list[str]
    warnings: list[ContextDataQualityWarning]
    routing_recommendations: list[ContextRoutingRecommendation]


class CustomerContextImportRequest(BaseModel):
    records: list[CustomerContextRecord]


class CustomerContextCsvImportRequest(BaseModel):
    csv_text: str = Field(min_length=1)


class CustomerContextImportResult(BaseModel):
    imported: int
    updated: int
    total_context_records: int


class CustomerContextValidationReport(BaseModel):
    valid: bool
    total_rows: int
    importable_rows: int
    errors: list[SignalValidationIssue]
    warnings: list[SignalValidationIssue]


class ContextCompletenessMetric(BaseModel):
    field: str
    label: str
    populated_records: int = Field(ge=0)
    total_records: int = Field(ge=0)
    coverage: float = Field(ge=0.0, le=1.0)
    importance: str


class CustomerContextCompletenessReport(BaseModel):
    total_records: int = Field(ge=0)
    total_accounts: int = Field(ge=0)
    complete_records: int = Field(ge=0)
    readiness_score: float = Field(ge=0.0, le=1.0)
    readiness_level: str
    metrics: list[ContextCompletenessMetric]
    warnings: list[SignalValidationIssue]


class DemoDatasetSummary(BaseModel):
    dataset_id: str
    title: str
    description: str
    industry: str
    signal_count: int
    context_count: int
    journeys: list[str]


class DemoDataset(BaseModel):
    dataset_id: str
    title: str
    description: str
    industry: str
    signals: list[SignalRecord]
    customer_context: list[CustomerContextRecord]


class DemoDatasetImportResult(BaseModel):
    dataset_id: str
    title: str
    signals: SignalImportResult
    customer_context: CustomerContextImportResult


class ProblemCandidate(BaseModel):
    candidate_id: str
    title: str
    journey: str
    journey_stage: str
    signal_count: int
    customer_count: int
    account_count: int
    sources: list[str]
    languages: list[str]
    first_seen: str
    last_seen: str
    confidence: float = Field(ge=0.0, le=1.0)
    evidence: list[Evidence]
    root_cause_hypothesis: str
    root_cause_analysis: RootCauseAnalysis | None = None
    suggested_owner: str
    suggested_action: str
    taxonomy_version: str | None = None
    classifications: list[TaxonomyClassification] = Field(default_factory=list)
    terminology_hits: list[str] = Field(default_factory=list)
    contradictory_evidence: list[str] = Field(default_factory=list)
    known_limitations: list[str] = Field(default_factory=list)
    evaluation_notes: list[str] = Field(default_factory=list)
    emerging_problem_score: float = Field(default=0.0, ge=0.0, le=1.0)
    review_status: CandidateReviewStatus = CandidateReviewStatus.pending
    duplicate_problem_id: str | None = None
    duplicate_reason: str | None = None
    reviewer: str | None = None
    review_note: str | None = None
    reviewed_at: str | None = None


class EmergingProblemSignal(BaseModel):
    candidate_id: str
    title: str
    journey: str
    journey_stage: str
    emerging_score: float = Field(ge=0.0, le=1.0)
    trend_label: str
    signal_count: int = Field(ge=0)
    source_count: int = Field(ge=0)
    customer_count: int = Field(ge=0)
    account_count: int = Field(ge=0)
    first_seen: str
    last_seen: str
    taxonomy_labels: list[str] = Field(default_factory=list)
    drivers: list[str] = Field(default_factory=list)
    recommended_next_step: str


class EmergingProblemReport(BaseModel):
    generated_at: str
    candidate_count: int = Field(ge=0)
    watch_count: int = Field(ge=0)
    action_count: int = Field(ge=0)
    signals: list[EmergingProblemSignal] = Field(default_factory=list)


class RuleCondition(BaseModel):
    field: str = ""
    operator: str = "equals"
    value: str = ""


class RuleAction(BaseModel):
    type: str = ""
    target: str = ""


class FeedbackRule(BaseModel):
    rule_id: str
    name: str
    conditions: list[RuleCondition] = Field(default_factory=list)
    actions: list[RuleAction] = Field(default_factory=list)
    priority: int = 0
    is_active: bool = True


class FeedbackRuleCreate(BaseModel):
    name: str = Field(min_length=1)
    conditions: list[RuleCondition] = Field(default_factory=list)
    actions: list[RuleAction] = Field(default_factory=list)
    priority: int = 0
    is_active: bool = True
